# Node.js 최신 LTS 버전 사용 (예: 20)
FROM node:18

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json 복사
COPY package.json .

# 의존성 설치
RUN npm install

# pm2 전역 설치
RUN npm install -g pm2

# 프로젝트 파일 전체 복사
COPY . .

# pm2로 애플리케이션 실행
CMD ["pm2-runtime", "npm", "--name", "my-app", "--", "start"]
