# Generated by Django 5.1.6 on 2025-02-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CowEstrusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=50)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('activity_level', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_estrus', models.BooleanField(null=True)),
                ('cctv_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cow_estrus_data',
            },
        ),
    ]
